import { StaticContentPage } from '@/components/StaticContentPage';

const ProvablyFair = () => (
  <StaticContentPage
    title="Provably Fair"
    lastUpdated="January 15, 2026"
    sections={[
      {
        title: 'What is Provably Fair?',
        content: (
          <div className="space-y-3">
            <p>Provably Fair is a cryptographic technology that allows you to independently verify the fairness of every game outcome on PhiBet.io. Unlike traditional online casinos where you must trust that the platform is fair, Provably Fair provides mathematical proof that game results have not been tampered with.</p>
            <p>This system ensures that neither PhiBet.io nor the player can predict or manipulate the outcome of any game before it occurs.</p>
          </div>
        ),
      },
      {
        title: 'How It Works',
        content: (
          <div className="space-y-3">
            <p>The Provably Fair system uses a combination of three elements to generate each game outcome:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Server Seed:</strong> A random string generated by our server before each game round. The SHA-256 hash of this seed is shown to you before the game starts, but the actual seed is kept hidden until after the round.</li>
              <li><strong>Client Seed:</strong> A random string provided by you (or auto-generated by your browser). You can change this at any time, giving you direct influence over the game outcome.</li>
              <li><strong>Nonce:</strong> A counter that increments with each bet, ensuring a unique result for every round even if the seeds remain the same.</li>
            </ul>
          </div>
        ),
      },
      {
        title: 'Verification Process',
        content: (
          <div className="space-y-3">
            <p>After each game round, you can verify the fairness by following these steps:</p>
            <ol className="list-decimal pl-5 space-y-2">
              <li><strong>Before the game:</strong> You receive the hash (SHA-256) of the server seed. This locks in the server's commitment - it cannot be changed after you see it.</li>
              <li><strong>During the game:</strong> Your client seed and the current nonce are combined with the server seed to produce the game result.</li>
              <li><strong>After the game:</strong> The actual server seed is revealed. You can hash it yourself and compare it to the hash shown before the game to confirm it wasn't changed.</li>
              <li><strong>Combine and verify:</strong> Using the server seed, client seed, and nonce, you can recalculate the game result yourself using standard SHA-256/HMAC algorithms.</li>
            </ol>
          </div>
        ),
      },
      {
        title: 'Server & Client Seeds',
        content: (
          <div className="space-y-3">
            <p><strong>Server Seed:</strong> Generated using a cryptographically secure random number generator (CSPRNG). A new server seed is created periodically or when you request it. The previous server seed is always revealed when a new one is generated.</p>
            <p><strong>Client Seed:</strong> You can view and change your client seed at any time in your account settings. We recommend changing it periodically for additional security. If you don't set one, a random client seed is generated for you automatically.</p>
            <p><strong>Nonce:</strong> Starts at 0 for each new seed pair and increments by 1 with each bet. This ensures every single bet produces a unique, verifiable result.</p>
          </div>
        ),
      },
      {
        title: 'Hash Verification',
        content: (
          <div className="space-y-3">
            <p>To verify a game result independently, you can use any SHA-256 hash tool (available online or through programming libraries). The verification formula is:</p>
            <div className="bg-background rounded-lg p-3 font-mono text-xs">
              <p>result = HMAC_SHA256(server_seed, client_seed + ":" + nonce)</p>
            </div>
            <p>The resulting hash is then converted to a game outcome (e.g., a number between 0-1 for crash games, or card values for card games) using a deterministic algorithm specific to each game type.</p>
            <p>You can find the seeds, nonces, and hashes for all your previous games in your bet history.</p>
          </div>
        ),
      },
      {
        title: 'Third-Party Audits',
        content: (
          <div className="space-y-3">
            <p>In addition to the Provably Fair system, our games from third-party providers are independently audited and certified by licensed testing laboratories. These audits verify:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Random Number Generator (RNG) integrity and unpredictability</li>
              <li>Game mathematics and return-to-player (RTP) accuracy</li>
              <li>Compliance with gaming regulations and standards</li>
              <li>Software security and data protection measures</li>
            </ul>
          </div>
        ),
      },
      {
        title: 'Transparency Commitment',
        content: (
          <p>PhiBet.io is committed to full transparency in all gaming operations. We believe that trust is built through verifiable proof, not promises. If you have any questions about our Provably Fair system or want assistance verifying a game result, our support team is available 24/7 to help.</p>
        ),
      },
    ]}
  />
);

export default ProvablyFair;
